apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: k8s-autoscaler-benchmarker
spec:
  template:
    metadata:
      labels:
        eks.autify.com/k8s-autoscaler-benchmarker: "true"
    spec:
      taints:
      - key: eks.autify.com/k8s-autoscaler-benchmarker
        effect: NoSchedule
      requirements:
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["t3.medium"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: k8s-autoscaler-benchmarker
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 5s
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: k8s-autoscaler-benchmarker
spec:
  amiFamily: Bottlerocket
  role: "KarpenterNodeRole-<YOUR_CLUSTER_NAME>"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: <YOUR_CLUSTER_NAME>
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: <YOUR_CLUSTER_NAME>